# Generated by Django 3.0.3 on 2020-02-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
    ]
